"""marketplace: add service catalog and CA prices

Revision ID: 51313df55ef5
Revises: 054952ac5c6b
Create Date: 2026-09-26 22:52:44.052665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51313df55ef5'
down_revision = '054952ac5c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('unit', sa.Enum('per_return', 'per_month', 'per_year', 'one_time', 'per_notice', name='service_unit', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_catalog')),
    sa.UniqueConstraint('code', name=op.f('uq_service_catalog_code'))
    )
    op.create_table('ca_services',
    sa.Column('ca_profile_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_ca_services_positive_price')),
    sa.ForeignKeyConstraint(['ca_profile_id'], ['ca_profiles.id'], name=op.f('fk_ca_services_ca_profile_id_ca_profiles')),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], name=op.f('fk_ca_services_service_id_service_catalog')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ca_services')),
    sa.UniqueConstraint('ca_profile_id', 'service_id', name=op.f('uq_ca_services_ca_profile_id'))
    )
    with op.batch_alter_table('ca_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ca_services_ca_profile_id'), ['ca_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ca_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ca_services_ca_profile_id'))

    op.drop_table('ca_services')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
