"""marketplace: add ca_profiles

Revision ID: 054952ac5c6b
Revises: b946ebd66628
Create Date: 2026-09-26 19:25:17.301966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '054952ac5c6b'
down_revision = 'b946ebd66628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('membership_no', sa.String(length=6), nullable=False),
    sa.Column('cop_number', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('specializations', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=500), server_default='', nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='ca_verification_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("languages <@ ARRAY['english', 'hindi', 'bengali', 'gujarati', 'kannada', 'malayalam', 'marathi', 'odia', 'punjabi', 'tamil', 'telugu', 'urdu']::varchar[]", name=op.f('ck_ca_profiles_known_languages')),
    sa.CheckConstraint("specializations <@ ARRAY['itr', 'gstr_1', 'gstr_3b', 'cmp_08', 'gstr_4', 'tds_24q', 'tds_26q', 'gst_registration', 'tax_audit', 'accounting_bookkeeping', 'income_tax_notices', 'company_llp_compliance', 'startup_msme_advisory']::varchar[]", name=op.f('ck_ca_profiles_known_specializations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ca_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ca_profiles')),
    sa.UniqueConstraint('membership_no', name=op.f('uq_ca_profiles_membership_no')),
    sa.UniqueConstraint('user_id', name=op.f('uq_ca_profiles_user_id'))
    )
    with op.batch_alter_table('ca_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_ca_profiles_specializations', ['specializations'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ca_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_ca_profiles_specializations', postgresql_using='gin')

    op.drop_table('ca_profiles')
    # ### end Alembic commands ###
