"""onboarding: QRMP choice and audit under another law

Revision ID: 492cdc20f226
Revises: f7cf22ea78de
Create Date: 2026-09-27 19:10:15.321544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492cdc20f226'
down_revision = 'f7cf22ea78de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_qrmp', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('accounts_audited_other_law', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('regulatory_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_audit_applicable', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###

    # Hand-written: existing businesses keep their profile until they edit it.
    # Businesses the app put on QRMP (it was automatic) count as having chosen it.
    op.execute(
        "UPDATE businesses SET gst_qrmp = true WHERE id IN "
        "(SELECT business_id FROM regulatory_profiles WHERE gst_scheme = 'regular_qrmp')"
    )
    # Companies' accounts are always audited under company law.
    op.execute(
        "UPDATE regulatory_profiles SET other_audit_applicable = true WHERE business_id IN "
        "(SELECT id FROM businesses WHERE entity_type = 'private_limited')"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regulatory_profiles', schema=None) as batch_op:
        batch_op.drop_column('other_audit_applicable')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('accounts_audited_other_law')
        batch_op.drop_column('gst_qrmp')

    # ### end Alembic commands ###
