"""marketplace: add engagement_items.quoted_price

Revision ID: f7cf22ea78de
Revises: b88770d4eef0
Create Date: 2026-09-27 17:54:04.622241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cf22ea78de'
down_revision = 'b88770d4eef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quoted_price', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###
    # Hand-written: autogenerate does not detect CHECK constraints.
    op.create_check_constraint(
        op.f('ck_engagement_items_quoted_price_not_negative'),
        'engagement_items',
        'quoted_price IS NULL OR quoted_price >= 0',
    )


def downgrade():
    # Hand-written: the CHECK constraint added by upgrade().
    op.drop_constraint(
        op.f('ck_engagement_items_quoted_price_not_negative'), 'engagement_items', type_='check'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_items', schema=None) as batch_op:
        batch_op.drop_column('quoted_price')

    # ### end Alembic commands ###
