"""marketplace: add pro_bono_requests.compliance_item_ids

Revision ID: f572fd37e925
Revises: 492cdc20f226
Create Date: 2026-09-28 08:48:17.340757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f572fd37e925'
down_revision = '492cdc20f226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_bono_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_item_ids', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro_bono_requests', schema=None) as batch_op:
        batch_op.drop_column('compliance_item_ids')

    # ### end Alembic commands ###
