"""onboarding: add gst_composition to businesses

Revision ID: b88770d4eef0
Revises: 827fb4ae8cbb
Create Date: 2026-09-27 13:45:47.575878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88770d4eef0'
down_revision = '827fb4ae8cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_composition', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('gst_composition')

    # ### end Alembic commands ###
