"""alerts: nullable penalty amounts and flat late fee

Revision ID: 9b1b07cafddc
Revises: f572fd37e925
Create Date: 2026-09-28 10:28:26.721754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1b07cafddc'
down_revision = 'f572fd37e925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalty_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flat_late_fee', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.alter_column('late_fee_per_day',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('annual_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)

    # ### end Alembic commands ###
    # Hand-written: autogenerate does not detect CHECK constraints.
    op.create_check_constraint(
        op.f('ck_penalty_rules_flat_late_fee_not_negative'),
        'penalty_rules',
        'flat_late_fee IS NULL OR flat_late_fee >= 0',
    )


def downgrade():
    # Fails while a rule has an empty per-day fee or interest rate (fill or delete it first).
    op.drop_constraint(op.f('ck_penalty_rules_flat_late_fee_not_negative'), 'penalty_rules')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalty_rules', schema=None) as batch_op:
        batch_op.alter_column('annual_interest_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('late_fee_per_day',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.drop_column('flat_late_fee')

    # ### end Alembic commands ###
